"use client"

import { useMemo, useState } from "react"
import { motion } from "framer-motion"
import { DashboardSidebar } from "@/components/dashboard/sidebar"
import { DashboardHeader } from "@/components/dashboard/header"
import { Button } from "@/components/ui/button"
import {
  ArrowRight, Building2, Check, ChevronDown, Download, Filter, Globe2, Mail, MapPin, Phone,
  Plus, Save, Search, SlidersHorizontal, Sparkles, Trash2, Users, X
} from "lucide-react"

const sections = [
  { id: "local", title: "Localização", description: "Encontre leads por região e proximidade", icon: MapPin },
  { id: "profile", title: "Perfil do Lead", description: "Defina o perfil ideal de cliente", icon: Users },
  { id: "company", title: "Empresa", description: "Segmente por porte e categoria", icon: Building2 },
  { id: "contact", title: "Dados de contato", description: "Escolha canais disponíveis", icon: Phone },
  { id: "digital", title: "Presença Digital", description: "Avalie a maturidade digital", icon: Globe2 },
  { id: "intent", title: "Intenção e comportamento", description: "Priorize oportunidades comerciais", icon: Sparkles },
  { id: "quality", title: "Qualidade do Lead", description: "Refine score e completude", icon: Check },
]

const leads = [
  ["Clínica Alpha", "João Silva", "Administrador", "Rio Claro - SP", "Saúde", "(19) 99999-9999", "4.8", "92", "Novo"],
  ["Odonto Vida", "Mariana Costa", "Proprietária", "Campinas - SP", "Saúde", "(19) 98888-7777", "4.7", "89", "Novo"],
  ["Instituto Bem Estar", "Carlos Mendes", "Diretor", "Piracicaba - SP", "Saúde", "(19) 97777-6666", "4.9", "87", "Em análise"],
  ["Centro Médico Norte", "Ana Paula", "Sócia", "São Paulo - SP", "Saúde", "(11) 96666-5555", "4.6", "84", "Novo"],
  ["Clínica Sorriso", "Pedro Lima", "Gerente", "Campinas - SP", "Saúde", "(19) 95555-4444", "4.8", "82", "Novo"],
]

export function AdvancedProspectingPage() {
  const [open, setOpen] = useState<string[]>(["local", "profile"])
  const [selected, setSelected] = useState(["São Paulo", "Saúde", "WhatsApp", "Score > 80"])
  const [loading, setLoading] = useState(false)
  const [modal, setModal] = useState<"save" | "generate" | null>(null)
  const [drawer, setDrawer] = useState(false)
  const [destination, setDestination] = useState("lista")
  const [minScore, setMinScore] = useState(80)

  const estimate = useMemo(() => Math.max(12483 - (selected.length - 4) * 836 - Math.max(0, minScore - 80) * 112, 0), [selected, minScore])
  const toggle = (id: string) => setOpen((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id])
  const addFilter = (filter: string) => setSelected((items) => items.includes(filter) ? items : [...items, filter])
  const removeFilter = (filter: string) => setSelected((items) => items.filter((item) => item !== filter))
  const search = () => { setLoading(true); window.setTimeout(() => setLoading(false), 650) }

  const FilterPanel = () => (
    <div className="space-y-3">
      {sections.map(({ id, title, description, icon: Icon }) => {
        const isOpen = open.includes(id)
        return <div key={id} className="overflow-hidden rounded-2xl border border-border bg-card">
          <button onClick={() => toggle(id)} className="flex w-full items-center gap-3 p-4 text-left hover:bg-secondary/50" aria-expanded={isOpen}>
            <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></span>
            <span className="min-w-0 flex-1"><span className="block font-semibold text-foreground">{title}</span><span className="block truncate text-xs text-muted-foreground">{description}</span></span>
            {id === "local" && <span className="rounded-full bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">3 ativos</span>}
            <ChevronDown className={`h-4 w-4 text-muted-foreground transition-transform ${isOpen ? "rotate-180" : ""}`} />
          </button>
          {isOpen && <div className="border-t border-border p-4 space-y-4">
            {id === "local" && <><Field label="País"><select className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20"><option>Brasil</option></select></Field><Field label="Estado"><select className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20"><option>São Paulo</option><option>Minas Gerais</option><option>Paraná</option></select></Field><Field label="Cidade"><div className="flex flex-wrap gap-2"><Chip label="São Paulo" onRemove={() => removeFilter("São Paulo")} /><Chip label="Campinas" /><Chip label="Rio Claro" /></div></Field><Field label="Região / Bairro"><input className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="Buscar região ou bairro" /></Field><label className="flex items-center gap-2 text-sm text-muted-foreground"><input type="checkbox" className="accent-primary" /> Usar localização do estabelecimento</label></>}
            {id === "profile" && <><Field label="Faixa etária"><div className="grid grid-cols-2 gap-2"><input className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="18 anos" /><input className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="65 anos" /></div></Field><Field label="Sexo"><div className="flex gap-2">{["Todos", "Masculino", "Feminino"].map((item) => <button key={item} onClick={() => addFilter(item)} className="rounded-lg bg-secondary px-3 py-2 text-xs font-medium text-foreground hover:text-primary">{item}</button>)}</div></Field><Field label="Profissão / Cargo"><input className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="Buscar cargo" /></Field><Field label="Faixa de renda"><select className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20"><option>Selecionar faixa de renda</option><option>R$ 5.000 – R$ 10.000</option><option>Acima de R$ 20.000</option></select></Field></>}
            {id === "company" && <><Field label="Segmento / Categoria"><select className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20"><option>Saúde</option><option>Educação</option><option>Varejo</option></select></Field><Field label="Número de funcionários"><select className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20"><option>1–10</option><option>11–50</option><option>51–200</option><option>500+</option></select></Field><Field label="Tipo de empresa"><div className="flex flex-wrap gap-2">{["MEI", "Microempresa", "Pequena", "Média", "Grande"].map((x) => <button key={x} onClick={() => addFilter(x)} className="rounded-lg border border-border px-2.5 py-1.5 text-xs text-muted-foreground hover:border-primary hover:text-primary">{x}</button>)}</div></Field></>}
            {id === "contact" && <div className="space-y-3">{["Possui WhatsApp", "Possui telefone", "Possui e-mail", "Contato verificado"].map((x) => <label key={x} className="flex items-center justify-between text-sm text-foreground"><span>{x}</span><input type="checkbox" defaultChecked={x === "Possui WhatsApp" || x === "Possui e-mail"} className="h-4 w-4 accent-primary" /></label>)}</div>}
            {id === "digital" && <><Field label="Avaliação no Google"><div className="grid grid-cols-2 gap-2"><input className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="Nota mínima: 4.0" /><input className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20" placeholder="Nota máxima: 5.0" /></div></Field><Field label="Canais digitais"><div className="flex flex-wrap gap-2">{["Instagram", "Facebook", "Site", "Google Meu Negócio"].map((x) => <button key={x} onClick={() => addFilter(x)} className="rounded-lg bg-secondary px-3 py-2 text-xs text-muted-foreground hover:text-primary">{x}</button>)}</div></Field></>}
            {id === "intent" && <><Field label="Potencial de oportunidade"><input type="range" min="0" max="100" defaultValue="72" className="w-full accent-primary" /><div className="flex justify-between text-xs text-muted-foreground"><span>Baixo</span><span>Alto</span></div></Field><div className="grid grid-cols-1 gap-2">{["Empresas sem site", "Presença digital fraca", "Empresas em crescimento"].map((x) => <button key={x} onClick={() => addFilter(x)} className="flex items-center justify-between rounded-lg border border-border p-2.5 text-left text-xs text-muted-foreground hover:border-primary hover:text-foreground">{x}<Plus className="h-3.5 w-3.5" /></button>)}</div></>}
            {id === "quality" && <><Field label={`Score mínimo: ${minScore}`}><input type="range" min="0" max="100" value={minScore} onChange={(e) => setMinScore(Number(e.target.value))} className="w-full accent-primary" /></Field>{["Somente leads verificados", "Somente dados completos", "Excluir duplicados", "Excluir já contatados"].map((x) => <label key={x} className="flex items-center justify-between text-sm text-foreground"><span>{x}</span><input type="checkbox" defaultChecked className="h-4 w-4 accent-primary" /></label>)}</>}
          </div>}
        </div>
      })}
      <button className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-primary/50 p-3 text-sm font-medium text-primary hover:bg-primary/5"><Plus className="h-4 w-4" /> Adicionar filtro personalizado</button>
    </div>
  )

  return <div className="min-h-screen bg-background"><DashboardSidebar /><div className="campaign-light min-h-screen bg-background transition-all duration-300 lg:ml-64"><DashboardHeader /><main className="p-4 sm:p-6 lg:p-8">
    <motion.div initial={{ opacity: 0, y: -10 }} animate={{ opacity: 1, y: 0 }} className="mb-7 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-primary"><SlidersHorizontal className="h-4 w-4" /> Sales intelligence</div><h1 className="text-3xl font-bold tracking-tight text-foreground">Prospecção <span className="font-normal text-muted-foreground">Avançada</span></h1><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Encontre os leads certos usando filtros precisos de localização, perfil, empresa e comportamento.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" className="text-foreground" onClick={() => setModal("save")}><Save className="mr-2 h-4 w-4" /> Salvar segmento</Button><Button variant="outline" className="text-foreground" onClick={() => setSelected([])}>Limpar filtros</Button><Button onClick={search}><Search className="mr-2 h-4 w-4" /> Buscar leads</Button></div></motion.div>
    <div className="mb-5 flex items-center justify-between xl:hidden"><Button variant="outline" onClick={() => setDrawer(true)}><Filter className="mr-2 h-4 w-4" /> Filtros</Button><span className="text-sm text-muted-foreground">{selected.length} filtros ativos</span></div>
    <div className="grid gap-6 xl:grid-cols-[minmax(300px,35%)_1fr]"><aside className="hidden xl:block"><FilterPanel /></aside><section className="min-w-0">
      <div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[[estimate.toLocaleString("pt-BR"), "Leads encontrados", Users], ["9.821", "Com telefone", Phone], ["7.432", "Com WhatsApp", Phone], ["6.908", "Com e-mail", Mail]].map(([value, label, Icon]) => <div key={String(label)} className="rounded-2xl border border-border bg-card p-4"><div className="mb-3 flex items-center justify-between"><Icon className="h-4 w-4 text-primary" /><span className="h-2 w-2 rounded-full bg-primary" /></div><p className="text-xl font-bold text-foreground sm:text-2xl">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div>
      <div className="mb-4 rounded-2xl border border-border bg-card p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-foreground">{loading ? "Atualizando estimativa..." : `${estimate.toLocaleString("pt-BR")} leads correspondem aos filtros selecionados`}</p><p className="mt-1 text-xs text-muted-foreground">Estimativa em tempo real baseada na sua segmentação</p></div><Button variant="ghost" className="text-foreground hover:text-primary" size="sm" onClick={() => setSelected([])}>Limpar filtros</Button></div><div className="mt-3 flex flex-wrap gap-2">{selected.length ? selected.map((x) => <Chip key={x} label={x} onRemove={() => removeFilter(x)} />) : <span className="text-xs text-muted-foreground">Nenhum filtro ativo</span>}</div></div>
      <div className="overflow-hidden rounded-2xl border border-border bg-card"><div className="flex flex-col gap-3 border-b border-border p-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold text-foreground">Pré-visualização dos leads</h2><p className="text-sm text-muted-foreground">1–50 de {estimate.toLocaleString("pt-BR")} leads</p></div><Button variant="outline" className="text-foreground" size="sm"><Download className="mr-2 h-4 w-4" /> Exportar</Button></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-secondary/50 text-xs uppercase tracking-wide text-muted-foreground"><tr>{["", "Empresa", "Responsável", "Cargo", "Cidade", "Segmento", "Avaliação", "Score", "Status"].map((x) => <th key={x} className="px-4 py-3 font-medium">{x}</th>)}</tr></thead><tbody className="divide-y divide-border">{leads.map((lead) => <tr key={lead[0]} className="hover:bg-secondary/30"> <td className="px-4 py-4"><input type="checkbox" className="h-4 w-4 accent-primary" /></td>{lead.map((value, i) => <td key={i} className={`whitespace-nowrap px-4 py-4 ${i === 0 ? "font-semibold text-foreground" : "text-muted-foreground"}`}>{i === 7 ? <span className="font-bold text-primary">{value}</span> : i === 8 ? <span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">{value}</span> : value}</td>)}</tr>)}</tbody></table></div><div className="flex items-center justify-between border-t border-border p-4 text-sm text-muted-foreground"><span>Página 1 de 250</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled>Anterior</Button><Button variant="outline" size="sm">Próxima <ArrowRight className="ml-2 h-4 w-4" /></Button></div></div></div>
      <div className="mt-6 grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-5"><h2 className="font-semibold text-foreground">Destino dos leads</h2><p className="mt-1 text-sm text-muted-foreground">Escolha o próximo passo da sua prospecção</p><div className="mt-4 space-y-2">{[["lista", "Apenas gerar lista"], ["crm", "Enviar para CRM"], ["pipeline", "Enviar automaticamente para pipeline"]].map(([id, label]) => <label key={id} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm ${destination === id ? "border-primary bg-primary/5 text-foreground" : "border-border text-muted-foreground"}`}><input type="radio" name="destination" value={id} checked={destination === id} onChange={() => setDestination(id)} className="accent-primary" />{label}</label>)}</div></div><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-foreground">Segmentos salvos</h2><p className="mt-1 text-sm text-muted-foreground">Acesse suas segmentações recorrentes</p></div><Button variant="ghost" size="sm">Ver todos</Button></div><div className="mt-4 space-y-3">{[["Clínicas Premium", "4.821 leads", "hoje"], ["Restaurantes sem site", "2.341 leads", "ontem"]].map(([name, count, date]) => <div key={name} className="flex items-center gap-3 rounded-xl bg-secondary/50 p-3"><span className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary/10 text-primary"><Filter className="h-4 w-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium text-foreground">{name}</p><p className="text-xs text-muted-foreground">{count} · atualizado {date}</p></div><button className="text-muted-foreground hover:text-foreground" aria-label={`Excluir ${name}`}><Trash2 className="h-4 w-4" /></button></div>)}</div></div></div>
      <div className="sticky bottom-4 z-10 mt-6 flex flex-col gap-3 rounded-2xl border border-primary/20 bg-card/95 p-4 shadow-xl backdrop-blur sm:flex-row sm:items-center sm:justify-between"><div><p className="font-semibold text-foreground">Pronto para prospectar?</p><p className="text-sm text-muted-foreground">{estimate.toLocaleString("pt-BR")} leads serão processados</p></div><Button onClick={() => setModal("generate")} size="lg">Gerar prospecção <ArrowRight className="ml-2 h-4 w-4" /></Button></div>
    </section></div>
  </main></div>
  {drawer && <div className="fixed inset-0 z-[60] xl:hidden"><div className="absolute inset-0 bg-background/70" onClick={() => setDrawer(false)} /><div className="absolute inset-y-0 left-0 w-[min(92vw,380px)] overflow-y-auto bg-background p-4 shadow-2xl"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-bold text-foreground">Filtros avançados</h2><Button variant="ghost" size="icon" onClick={() => setDrawer(false)}><X className="h-5 w-5" /></Button></div><FilterPanel /></div></div>}
  {modal && <div className="fixed inset-0 z-[70] flex items-center justify-center bg-background/70 p-4"><div className="w-full max-w-md rounded-2xl border border-border bg-card p-6 shadow-2xl"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-xl font-bold text-foreground">{modal === "save" ? "Salvar segmento" : "Pronto para prospectar?"}</h2><p className="mt-1 text-sm text-muted-foreground">{modal === "save" ? "Guarde esta combinação de filtros para usar depois." : "Confirme os filtros antes de iniciar."}</p></div><button onClick={() => setModal(null)} aria-label="Fechar"><X className="h-5 w-5 text-muted-foreground" /></button></div>{modal === "save" ? <div className="space-y-4"><Field label="Nome do segmento"><input className="h-10 w-full rounded-lg border border-border bg-background px-3 text-sm text-foreground shadow-sm outline-none transition-colors placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-primary/20" defaultValue="Clínicas premium — Interior SP" /></Field><Field label="Descrição"><textarea className="input min-h-20" defaultValue="Leads com alto potencial comercial" /></Field></div> : <div className="rounded-xl bg-secondary/60 p-4 text-sm text-muted-foreground"><p>Filtros: <strong className="text-foreground">{selected.join(", ")}</strong></p><p className="mt-2">Leads estimados: <strong className="text-primary">{estimate.toLocaleString("pt-BR")}</strong></p></div>}<div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={() => setModal(null)}>Cancelar</Button><Button onClick={() => setModal(null)}>{modal === "save" ? "Salvar segmento" : "Iniciar prospecção"}</Button></div></div></div>}
  </div>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1.5"><span className="text-xs font-semibold text-foreground">{label}</span>{children}</label> }
function Chip({ label, onRemove }: { label: string; onRemove?: () => void }) { return <span className="inline-flex items-center gap-1 rounded-full bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">{label}{onRemove && <button onClick={onRemove} aria-label={`Remover ${label}`}><X className="h-3 w-3" /></button>}</span> }
